### ISSUE TITLE
X86PowerOff Icons are Completely Invisible

### ISSUE THREAD

**Issue by worsthrplayer** [sudoharun/dotfiles#3]
I used the default way of getting to the power menu and the icons are invisible and when i add a shortcut in my hyprland configs its still invisible, they do work though i just cant tell

i have the .svg icons in my dotfiles folder too, i dont know what the issue is

**Comment by sudoharun** [comment]
Hi, which branch is this?

**Comment by worsthrplayer** [comment]
> Hi @worsthrplayer, which branch is this?

retroesque.

**Comment by sudoharun** [comment]
Any errors in `eww logs`?

**Comment by worsthrplayer** [comment]
ive even tried reinstalling my entire os and switching to diff dotfile sand back

**Comment by worsthrplayer** [comment]
i have the .svg files in the .config/eww folders too, i checked the eww.yuck file and the lock shutdown reboot and hibernate icons are set to use the .svg files that are in the images folder in the .config directory.

**Comment by sudoharun** [comment]
@worsthrplayer Can you send screenshots please?

**Comment by worsthrplayer** [comment]
ok sorry for the bother but somehow the issue just managed to fix itself?? but i just have one more question. where are the screenshots saved?

**Comment by sudoharun** [comment]
Screenshots are saved to `$HOME/Pictures/Screenshots`. The folder has to exist for the screenshots to be saved. You can change the path in `$HOME/.config/scripts/screenshooter` if you wish to do so.

**Comment by worsthrplayer** [comment]
alright. can you help me figure out how to edit the config so that it copies to the clipboard?

**Comment by sudoharun** [comment]
`grim - | wl-copy` to screenshot the entire screen and copy it to clipboard, and
`grim -g "$(slurp)" - | wl-copy` to select a region and copy it to clipboard.

**Comment by worsthrplayer** [comment]
alright thanks.
